# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53a47c2b4954a14829d827fe146c7faae515df9a83966a7133f2b59a1e26abb741b72372e199468894da0f83e49ca432e0c6698ae61290e9630ac4334f143d4f

test:
  secret_key_base: 721d79d9f186482298f6ad8a30271baef69810afe99a693cb3826710ac1256c1ae32ffc64a4b74e22e9946287e633eced96f73d9b1b1bafeb68cbd140e6df60d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
